import type { Metadata } from "next";
import '@/views/style/global.scss'
import { Menu } from "@/widgets/menu/Menu";
import { ProviderWrapper } from "@/shared/wrappers/provider-wrapper/ProviderWrapper";

// if add next js font 
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
// <body className={inter.className}>{children}</body>

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProviderWrapper>
        <body>
          {children}
          <Menu />
        </body>
      </ProviderWrapper>
    </html>
  );
}
