import type { Metadata } from "next";
import '@/views/style/global.scss'
import { Menu } from "@/widgets/menu/Menu";
import { ProviderWrapper } from "@/shared/wrappers/provider-wrapper/ProviderWrapper";
import Head from "next/head";

// if add next js font 
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
// <body className={inter.className}>{children}</body>

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <script src="https://telegram.org/js/telegram-web-app.js?57" async></script>
      </Head>
      <ProviderWrapper>
        <body>
          {children}
          <Menu />
        </body>
      </ProviderWrapper>
    </html>
  );
}
